# 付款行（bank-a / ICBC）profile
server:
  port: 18081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gyd_c03_bank_a
    username: gyd
    password: gyd123
    driver-class-name: org.postgresql.Driver

gyd:
  c03:
    bank:
      code: ICBC
      queue: gyd.c03.settlement.bank-a