# 收款行（bank-b / CCB）profile
server:
  port: 18082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gyd_c02_bank_b
    username: gyd
    password: gyd123
    driver-class-name: org.postgresql.Driver

gyd:
  c02:
    bank:
      code: CCB
      queue: gyd.c02.settlement.bank-b